steps:
  - label: ":golang: Run Go Tests"
    command: |
      cd services/go-hello-world
      go test -v ./...
    plugins:
      - docker#v5.11.0:
          image: "golang:1.21"
          workdir: /app
          volumes:
            - ".:/app"

  - label: ":golang: Build Go Service"
    command: |
      cd services/go-hello-world
      go build -o bin/go-hello-world
    plugins:
      - docker#v5.11.0:
          image: "golang:1.21"
          workdir: /app
          volumes:
            - ".:/app"

