steps:
  - label: ":python: Ensure Dependencies Install"
    command: |
      cd services/python-hello-world
      pip install -r requirements.txt
    plugins:
      - docker#v5.11.0:
          image: "python:3.11"
          workdir: /app
          volumes:
            - ".:/app"

  - label: ":python: Run Python Tests"
    command: |
      cd services/python-hello-world
      pip install -r requirements.txt
      python -m unittest test_app.py -v
    plugins:
      - docker#v5.11.0:
          image: "python:3.11"
          workdir: /app
          volumes:
            - ".:/app"

  - label: ":python: Lint Python Code"
    command: |
      cd services/python-hello-world
      pip install -r requirements.txt
      pip install flake8
      flake8 app.py --max-line-length=100
    plugins:
      - docker#v5.11.0:
          image: "python:3.11"
          workdir: /app
          volumes:
            - ".:/app"
